### ISSUE TITLE
Focused Jasmine specs fail with error: Failed: expect(...).toMatchScreen is not a function

### ISSUE THREAD

**Issue by qualityshepherd** [koola/pix-diff#15]
**Steps:**
1. Assumes a Jasmine spec that uses pix-diff, with a `toMatchScreen()`
2. Focus spec by adding an `f` to the `describe` block (and thus run only that spec)
3. Run spec

**Results:**
The first spec after the `fdescribe` block will fail with: `- Failed: expect(...).toMatchScreen is not a function`. Specs after the first pass as expected. The same spec passes when run without focus. 

**Impact:**
This only seems to occur when focussing on a Jasmine spec, and then, only the first spec after a focussed describe block.  
Protractor 3.3.0; node:4.2.1; pix-diff: 1.0.10; Jasmine2.4.1

**Comment by koola** [comment]
I'll take a closer look at this when I've got some time. Expecting it's probably a jasmine issue relating to their custom matchers.

**Comment by kovacsbalu** [comment]
You need to specify framework. I don't know why but `_.framework` value is "jasmine" by default in pix-diff index.js.

`exports.config = {
  framework: "jasmine2",
  ...
  }`

**Comment by qualityshepherd** [comment]
This also occurs when sharding tests...

**Comment by koningskristof** [comment]
You could add a d.ts with this content:
```
declare module jasmine {
    interface Matchers {
        toMatchScreen(): boolean;
    }
}
```

But it would be nice to ship typings together with this project.

**Comment by josephlaw** [comment]
@koningskristof can you elaborate how to implement d.ts? 

Because I only can hardcode to add ` require('/xxxx/node_modules/pix-diff/framework/jasmine2')` into jasmine spec to fix this problem.

**Comment by koningskristof** [comment]
With typings you can set your typings-dependencies, but also include a local file as the source for a typing: https://github.com/typings/typings/blob/master/docs/commands.md

However it would be nice that the author of this project could ship this with a d.ts file, see http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by koola** [comment]
I'll take a look into this when time permits.

**Comment by johnvnguyen** [comment]
A quick work around is using `expect(...)['toMatchScreen']();` so you won't compilation errors.

**Comment by koola** [comment]
Ok, this happens when the matcher is loaded into a `beforeEach` as each matcher is already wrapped in a `beforeEach`.
Options are:

1. Split out loading the matchers in a separate function (would only need to be called once)

2. Remove the wrapped matchers, but then only instantiate PixDiff within a `beforeEach`

Option 1 looks cleaner to me.

**Comment by koola** [comment]
This is fixed in release. Now you need to call the static method `loadMatchers()` outside of the `beforeEach()`. The matchers name has changed to `toPass()`, see the examples for usage.

**Comment by qualityshepherd** [comment]
Yeah, while the example test I offered loaded the matchers in a `beforeEach`, in my _acutal_ code, it does not, and sadly, this is still an issue.

**Comment by qualityshepherd** [comment]
Here's an updated example test that displays the issue, and works with 1.2.2. Run on my retina macbook, chrome saves the png as `canvas-Test-chrome-2048x1554-dpr-2.png`... firefox saves pngs as `canvas-Test-firefox-1024x777-dpr-1.png`.

```
var PixDiff = require('pix-diff');
var jasmine = require('../../node_modules/pix-diff/framework/jasmine2');

describe('Pix-Diff', function() {

    beforeEach(function() {
        browser.pixdiff = new PixDiff({
            basePath: './',
            diffPath: './',
            width: 1024,
            height: 800
        });
    });
    
    it('should get canvas dimensions correctly', function() {
        var tag = 'canvas-test';

        browser.get('http://www.w3schools.com/html/html5_canvas.asp');
        browser.pixdiff.saveRegion($('#myCanvas'), tag);

        expect(browser.pixdiff.checkRegion($('#myCanvas'), tag)).toPass();
    });
});
```

**Comment by ignamiguel** [comment]
I believe that the problem is that you must specify the `framework: 'jasmine2'` parameter in protractor config file.
Then, the `toPass()` matcher is working ok.
Without the framework, is not
Hope this can help 👍
